openapi: 3.0.3
info:
  title: E-commerce API
  version: "1.0.0"
  description: API for managing products in an e-commerce system.
paths:
  /products:
    post:
      summary: Create a New Product
      operationId: createProduct
      requestBody:
        required: true
        description: Product information needed to create a new product.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductRequest'
      responses:
        '201':
          description: Product created successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductResponse'
        '400':
          description: Invalid product data provided.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /products/{productId}:
    get:
      summary: Get Product by ID
      operationId: getProduct
      parameters:
        - name: productId
          in: path
          required: true
          description: Unique identifier of the product.
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Product details retrieved successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductResponse'
        '404':
          description: Product not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    ProductRequest:
      type: object
      required:
        - name
        - price
        - category
      properties:
        name:
          type: string
          description: Name of the product.
          minLength: 3
          maxLength: 50
        price:
          type: number
          format: float
          description: Price of the product. Must be greater than 0.
          minimum: 0.01
        description:
          type: string
          description: Detailed description of the product.
          maxLength: 500
        category:
          $ref: '#/components/schemas/Category'
        tags:
          type: array
          description: List of tags for the product.
          items:
            type: string
        attributes:
          type: object
          description: A map of additional attribute names and values.
          additionalProperties:
            type: string
    ProductResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier of the product.
        name:
          type: string
          description: Name of the product.
        price:
          type: number
          description: Price of the product.
        description:
          type: string
          description: Detailed description of the product.
        category:
          $ref: '#/components/schemas/Category'
        tags:
          type: array
          description: List of tags associated with the product.
          items:
            type: string
        attributes:
          type: object
          description: Additional attributes provided for the product.
          additionalProperties:
            type: string
        createdAt:
          type: string
          description: Timestamp when the product was created.
    Category:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          description: Unique identifier of the category.
        name:
          type: string
          description: Name of the category.
        parentCategory:
          $ref: '#/components/schemas/CategoryReference'
          description: Reference to the parent category, if any.
        subCategories:
          type: array
          description: List of sub-categories.
          items:
            $ref: '#/components/schemas/CategoryReference'
    CategoryReference:
      type: object
      properties:
        id:
          type: integer
          description: Unique identifier of the category.
        name:
          type: string
          description: Name of the category.
    ErrorResponse:
      type: object
      properties:
        code:
          type: string
          description: Error code.
        message:
          type: string
          description: Detailed error message.
        details:
          type: array
          description: Additional error details.
          items:
            type: object
            properties:
              field:
                type: string
                description: The field where the error occurred.
              message:
                type: string
                description: Error message for the field.